[project]
name = "medical-image-analysis"
description = "A blockchain-based medical image analysis system using deep learning"
authors = []
telemetry = false
requirements = []
costs_version = 2
[contracts.medical-analysis]
path = "contracts/medical-analysis.clar"
clarity_version = 2
epoch = 2.1

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
